### ISSUE TITLE
Source() field sometimes is useless.

### ISSUE THREAD

**Issue by wicast** [seletskiy/go-makepkg#10]
Because when come to `go get`step,it would download the repo again in to `$GOPATH/src/path/to/repo` if the repo has some local import but written in a global path.

**Comment by seletskiy** [comment]
@wicast: can you clarify the case? I don't understand.

**Comment by wicast** [comment]
For example [hugo](https://github.com/spf13/hugo/blob/master/main.go#L19) is import a package called `github.com/spf13/hugo/commands` which is a local package for hugo.But in golang,it must use globe path which has complete domain namespace otherwise `go get` won't work.
In PKGBUILD,`$GOPATH` is set to a `.go` directory and `$GOPATH/src/github.com/spf13/hugo/command` doesn't exist.So that's the reason why the repo was downloaded again when running `makepkg`.

My suggestion is leave everything to `go get`,even the main project it self.

**Comment by seletskiy** [comment]
@wicast: I don't see a problem here. `go-makepkg -B "hugo" git://github.com/spf13/hugo` works fine.

**Comment by seletskiy** [comment]
@wicast: `GOPATH` is set to the local `.go` directory and it indeed will contain rudimentary `<pkgname>` directory, like `.go/src/hugo/`, but PKGBUILD is crafted in that way so `go get` will be executed inside the `.go/src/hugo/` with `GOPATH` set to `.go/`, so each import from source code will be fetched (including `spf13/hugo/commands`).

**Comment by wicast** [comment]
@seletskiy Yes,This doesn't fail you building process for `makepkg`.Actually it's not a big problem. 
But the in that situation,`.go/src/hugo/` is not reused when fetching `spf13/hugo/commands`.
When I was packaging `go-tools`,I manually [modified some code](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=go-tools#n58) to avoid re-download the whole repo.

So just remove the source() field is ok.I think `go get` is smart enough for downloading these repo.

**Comment by wicast** [comment]
ping.Any idea on this problem?

**Comment by seletskiy** [comment]
@wicast: I don't like removing `Source()` from `PKGBUILD`, because it will be lacking from AUR web interface then.

However, it can be done in the better way by creating symlink from cloned repo to target import path (quite trivial to do, I guess).

I don't feel urge to fix this particular issue, but if you want, you can do it and make PR, I'll glad to see it.
